# Behavior Driven Development (BDD) and Functional Testing
[Documentation]     Here are the img transform data Keywords implementation resources

*** Settings ***
Library                 String
Library                 ../../resources/customlib/StringExtended/StringExtended.py
Variables               ../common/selenium-resources/web-elements/extract-web-elements.yaml

*** Keywords ***
Xbox game catalog and img screenshot validate