[Documentation]     This resource get the getvalueResources.resource implementation


*** Keywords ***
# Extract the game data information on xbox game catalog title
#     Get the game data information
    

Read and extract the game data information by screenshot
    Read and extract the game data information

Transform the game data extraction to save
    Get the game extraction file to match with the game data input