[Documentation]     This resource get the web-gamectg-extract/web-gamectg-transform 
...                 resources implementation


*** Keywords ***
Extract the game data information on xbox game catalog title
    Get the game data detail information on xbox game catalog
    
Extract the game data information by screenshot
    Extract the game data detail information on img screenshot

Transform the game data extraction to save
    Get the game extraction file to match with the game data input