[Documentation]     This resource get the web-gamectg-extract/web-gamectg-transform 
...                 resources implementation


*** Keywords ***
Extract the game data information on xbox game catalog title
    Get the game data detail information on xbox game catalog
    
#Extract the game data information by screenshot
    #Get the game data detail information on img screenshot

#That the transform game data extraction was successfully
    #Transform the game data extraction to save

Transform the game data information
    get the game data variable to create the xml/json file
