name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
    build:
      # if: github.repository ==  ${{ secrets.SAP_AUTOMATION_POC_PATH }}
      runs-on: ubuntu-latest
      name: Run Robot Framework Tests
      steps:
        - name: Run SAP GUI NetWeaver Automation
          uses: actions/checkout@v2
        - name: Robot Framework
          uses: hcardamone/sap-automation-poc/.github/robotframework-docker-action@v1.0
          with:
            browser: 'firefox'
            robot_threads: 2
            robot_options:  --variablefile    ..\..\..\robot-variables\robot_variables.py --variablefile ..\..\..\..\resources\input-data\input-data-variables.py --loglevel TRACE --outputdir ..\..\..\results --include extract_transform_game_info --include load_game_info --exclude add_val_sapguitests .\demo.robot
            robot_tests_dir:    ${{ secrets.SAP_AUTOMATION_POC_PATH }}
            robot_reports_dir:  /resources/results